config/routes.rb
Rails.application.routes.draw do
  root :to => 'login#index'

  get 'login/login', :to => 'login#login'
  post 'login/do_login', :to => 'login#do_login'

  get  'login/admin_login', :to => 'login#admin_login'
  post 'login/do_admin_login', :to => 'login#do_admin_login'

  get 'proyectos/mis_proyectos', :to => 'proyectos#projects_for_user'
  post 'proyectos/remove_assignment', :to => 'proyectos#remove_user_from_wait_list'
  post 'proyectos/assign', :to => 'proyectos#add_user_to_wait_list'
  post 'proyectos/lista_espera', :to => 'proyectos#get_lista_espera_for_proyecto'
  post 'proyectos/asignar', :to => 'proyectos#approve_asignacion'

  get '/welcome/', :to => 'welcome#index'

  resources :welcome

  resources :dia_horas

  resources :horarios

  resources :proyecto_carreras

  resources :lista_espera_proyectos

  resources :admins

  resources :proyectos

  resources :ubicacions

  resources :carreras

  resources :usuarios

end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
  belongs_to :admin
  belongs_to :ubicacion

  has_many :proyecto_carreras
  has_many :carreras, :through => :proyecto_carreras

  has_many :horarios

  def self.search(query)
    where("nombre like ?", "%#{query}%")
  end
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_is_admin
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy]

  def set_is_admin
    @is_admin = session[:admin] != nil
  end

  # GET /proyectos
  # GET /proyectos.json
  def index
    if params[:name_search]
      @proyectos = Proyecto.search(params[:name_search])
    else
      @proyectos = Proyecto.all
    end
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end

  # GET /proyectos/1/edit
  def edit
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(proyecto_params)

    respond_to do |format|
      if @proyecto.save
        params[:proyecto][:carreras].each do |carrera|
          carrera = carrera.to_i
          if carrera > 0 # For some reason the first element in our array is an empty string, so we need to check for valid ids
            asignacion = ProyectoCarrera.new
            asignacion.proyecto = @proyecto
            asignacion.carrera  = Carrera.find(carrera)

            asignacion.save
          end
        end

        format.html { redirect_to @proyecto, notice: 'El proyecto se registró exitosamente' }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
    respond_to do |format|
      if @proyecto.update(proyecto_params)
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto.destroy
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: 'Se borró el proyecto exitosamente' }
      format.json { head :no_content }
    end
  end

  def projects_for_user
    usuario = Usuario.find params[:get][:usuario_id]
    @asignaciones = ListaEsperaProyecto.where(:usuario_id => usuario.id)
    render file: 'proyectos/projects_for_user'
  end

  def add_user_to_wait_list
    assignment = ListaEsperaProyecto.new
    assignment.usuario_id = params[:post][:usuario_id]
    assignment.horario_id = params[:post][:horario_id]
    assignment.aprobada   = false

    horas_registradas = 0
    assignment.usuario.horarios.each { |horario| horas_registradas += horario.proyecto.horas }

    # Dejar la lista de espera abierta aunque el proyecto este lleno
    # Ver la lista de espera por Orden de llegada
    # Permitir suscribirse a cambio de status de proyectos
    now = Time.now
    if now < assignment.horario.proyecto.registro_inicio
      redirect_to :back, notice:  'El horario de de registro aún no ha empezado.'
    elsif now > assignment.horario.proyecto.registro_fin
      redirect_to :back, notice:  'El registro para este para este proyecto ha finalizado.'
    elsif horas_registradas >= 240
      redirect_to :back, notice: 'Alcanzaste el límite de horas registradas'
    elsif ListaEsperaProyecto.where(:horario_id => assignment.horario.id, :aprobada => false).size >= (2 * assignment.horario.capacidad) # Wait list is twice the number of available spots
      redirect_to :back, notice: 'La lista de espera está llena'
    # elsif ListaEsperaProyecto.where(:horario_id => assignment.horario.id, :aprobada => true).size >= assignment.horario.capacidad
    #   redirect_to :back, notice: 'Ya no hay cupos en el proyecto'
    elsif assignment.save
      redirect_to :back, notice: 'Se añadió a la lista de espera exitosamente'
    else
      redirect_to :back, notice: 'Hubo un error al añadir a la lista de espera'
    end
  end

  def approve_asignacion
    assignment = ListaEsperaProyecto.find params[:post][:asignacion_id]
    assignment.aprobada = true
    @proyecto = Proyecto.find params[:post][:proyecto_id]

    horas_registradas = 0
    assignment.usuario.horarios.each { |horario| horas_registradas += horario.proyecto.horas }

    if horas_registradas >= 240
      flash[:notice] = 'El usuario alcanzó el límite de horas inscritas'
      render file: 'proyectos/lista_espera'
    elsif ListaEsperaProyecto.where(:horario_id => assignment.horario.id, :aprobada => true).size >= assignment.horario.capacidad
      flash[:notice] = 'Ya no hay cupos en el proyecto'
      render file: 'proyectos/lista_espera'
    elsif assignment.save
      flash[:notice] = 'Se aprobó la asignación exitosamente'
      render file: 'proyectos/lista_espera'
    else
      flash[:notice] = 'Hubo un error al añadir a la lista de espera'
      render file: 'proyectos/lista_espera'
    end
  end

  def remove_user_from_wait_list
    assignment = ListaEsperaProyecto.find params[:post][:asignacion_id]
    assignment.aprobada = false
    @proyecto = Proyecto.find params[:post][:proyecto_id]
    if assignment.delete
      flash[:notice] = 'Se quitó del proyecto exitosamente'
      render file: 'proyectos/lista_espera'
    else
      flash[:notice] = 'Hubo un error al quitarte de la lista de espera'
      render file: 'proyectos/lista_espera'
    end
  end

  def get_lista_espera_for_proyecto
    @proyecto = Proyecto.find params[:post][:proyecto_id]
    render file: 'proyectos/lista_espera'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      begin
        @proyecto = Proyecto.find(params[:id])
      rescue
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyecto_params
      params.require(:proyecto).permit(:nombre, :descripcion, :registro_inicio, :registro_fin, :ubicacion_id, :admin_id, :horas, :requisitos, :carreras, :semestre_minimo, :semestre_max)
    end
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/proyectos/_form.html.erb
<%= form_for(@proyecto) do |f| %>
  <% if @proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% @proyecto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :registro_inicio %><br>
    <%= f.datetime_select :registro_inicio %>
  </div>
  <div class="field">
    <%= f.label :registro_fin %><br>
    <%= f.datetime_select :registro_fin %>
  </div>
  <div class="field">
    <%= f.label :ubicacion_id %><br>
    <select name="proyecto[ubicacion_id]">
      <%
         Ubicacion.all.order(:iniciales).each do |ubicacion|
      %>
          <option value="<%= ubicacion.id %>"><%= "#{ubicacion.iniciales}" %></option>
      <%
         end
      %>
    </select>
  </div>
  <div class="field">
    <%= f.label :admin_id %><br>
    <%= f.select :admin_id, Admin.all.collect {|admin| ["#{admin.apellido} #{admin.nombre}", admin.id] } %>
  </div>
  <div class="field">
    <%= f.label :horas %><br>
    <%= f.number_field :horas %>
  </div>
  <div class="field">
    <%= f.label :requisitos %><br>
    <%= f.text_area :requisitos %>
  </div>
    <!-- Añadir botón para seleccionar todas las carreras -->
  <div class="field">
    <%= f.label :carreras %>
    <%= f.select :carreras, options_from_collection_for_select(Carrera.all.order(:iniciales), :id, :iniciales), {}, {:multiple => true} %>
  </div>
  <div class="field">
    <%= f.label 'Semestre mínimo' %>
    <%= f.number_field :semestre_minimo %>
  </div>
   <div class="field">
     <%= f.label 'Semestre máximo' %>
     <%= f.number_field :semestre_max %>
   </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<h1>Editing Proyecto</h1>

<%= render 'form' %>

<%= link_to 'Show', @proyecto %> |
<%= link_to 'Back', proyectos_path %>

app/views/proyectos/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Proyectos</h1>
<% if session[:admin] %>
    <%= link_to 'Nuevo Proyecto', new_proyecto_path %>
    <br>
<% end %>

<%= form_tag({:controller => 'proyectos', :action => 'index'}, :method => 'get') do %>
    <%= label_tag(:name_search, "Busqueda por nombre:") %>
    <%= text_field_tag(:name_search, params[:name_search]) %>
    <%= submit_tag 'Buscar', :name => nil %>
<% end %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Registro inicio</th>
      <th>Registro fin</th>
      <th>Ubicacion</th>
      <th>Admin</th>
      <th>Horas</th>
      <th>Carreras</th>
      <th>Semestres</th>
      <th>Requisitos</th>
    </tr>
  </thead>

  <tbody>
    <% @proyectos.each do |proyecto| %>
      <tr>
        <td> <%= link_to proyecto.nombre, proyecto %> </td>
        <td> <%= proyecto.descripcion %> </td>
        <td> <%= proyecto.registro_inicio.strftime '%d/%m/%Y %H:%M' %> </td>
        <td> <%= proyecto.registro_fin.strftime '%d/%m/%Y %H:%M' %> </td>
        <td>
          <% if proyecto.ubicacion %>
                <a href="<%= ubicacion_path proyecto.ubicacion.id %>"><%= proyecto.ubicacion.iniciales %></a>
          <% else %>
                <strong>N/A</strong>
          <% end %>
        </td>
        <td>
          <% if proyecto.admin %>
                <a href="<%= admin_path proyecto.admin.id %>"><%= "#{proyecto.admin.nombre} #{proyecto.admin.apellido}" %></a>
          <% else %>
                <strong>N/A</strong>
          <% end %>
        </td>
        <td><%= proyecto.horas %></td>
        <td>
          <% proyecto.carreras.each do |carrera| %>
            <%= "#{carrera.iniciales} " %>
          <% end %>
        </td>
        <td><%= "#{proyecto.semestre_minimo} - #{proyecto.semestre_max}" %></td>
        <td><%= proyecto.requisitos %></td>
        <% if session[:admin] %>
            <td><%= link_to 'Editar', edit_proyecto_path(proyecto) %></td>
            <td><%= link_to 'Borrar', proyecto, method: :delete, data: { confirm: 'Estás seguro de que quieres borrar este proyecto?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/proyectos/lista_espera.html.erb
<p id="notice"><%= notice %></p>
<h1>Lista de espera para <%= @proyecto.nombre %></h1>
<% @proyecto.horarios.each do |horario| %>
    <h2>
      <% horario.dia_horas.each do |dia_hora| %>
        <%= "#{dia_hora.to_s} " %>
      <% end %>
    </h2>
    <table>
      <th>Usuario</th>
      <th>Aprobado</th>
      <% ListaEsperaProyecto.where(:horario_id => horario.id).each do |asignacion| %>
        <tr>
          <td><%= link_to asignacion.usuario.nombre %></td>
          <td><%= asignacion.aprobada ? 'Sí' : 'No' %></td>
          <td>
            <% unless asignacion.aprobada %>
                <%= form_tag({:controller => 'proyectos', :action => 'approve_asignacion'}, :method => 'post') do %>
                    <%= hidden_field :post, :asignacion_id, :value => asignacion.id %>
                    <%= hidden_field :post, :proyecto_id, :value => asignacion.horario.proyecto.id %>
                    <%= submit_tag 'Aprobar' %>
                <% end %>
            <% end %>
            <% if asignacion.aprobada %>
                <%= form_tag({:controller => 'proyectos', :action => 'remove_user_from_wait_list'}, :method => 'post') do %>
                    <%= hidden_field :post, :asignacion_id, :value => asignacion.id %>
                    <%= hidden_field :post, :proyecto_id, :value => asignacion.horario.proyecto.id %>
                    <%= submit_tag 'Rechazar' %>
                <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
<% end %>

app/views/proyectos/new.html.erb
<h1>Nuevo Proyecto</h1>

<%= render 'form' %>

<%= link_to 'Regresar', proyectos_path %>

app/views/proyectos/projects_for_user.html.erb
<h1>Mis proyectos</h1>
<table>
  <tr>
      <th>Proyecto</th>
      <th>Horario</th>
      <th>Aprobado</th>
  </tr>
  <% @asignaciones.each do |a| %>
      <tr>
        <td><%= link_to a.horario.proyecto.nombre, a.horario.proyecto %></td>
        <td>
          <% a.horario.dia_horas.each do |dia_hora| %>
            <%=  "#{dia_hora.to_s}\n"  %>
          <% end %>
        </td>
        <td>
          <!-- Aprobada debe ser un ternary if: en espera, sí, no-->
          <%= a.aprobada ? 'Sí' : 'No' %>
        </td>
      </tr>
  <% end %>
</table>

app/views/proyectos/resultados_busqueda.html.erb
<h1>
  <%= @results.count %>
</h1>

app/views/proyectos/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @proyecto.nombre %></h1>

<p>
  <strong>Descripcion:</strong>
  <%= @proyecto.descripcion %>
</p>

<p>
  <strong>Registro inicia:</strong>
  <%= @proyecto.registro_inicio.strftime '%D/%m/%Y %H:%M' %>
</p>

<p>
  <strong>Registro termina:</strong>
  <%= @proyecto.registro_fin.strftime '%D/%m/%Y %H:%M' %>
</p>

<p>
  <strong>Ubicacion:</strong>
  <%= link_to @proyecto.ubicacion.name, @proyecto.ubicacion %>
</p>

<p>
  <strong>Administrador:</strong>
  <a href="<%= admin_path @proyecto.admin.id %>"><%= "#{@proyecto.admin.nombre} #{@proyecto.admin.apellido}" %></a>
</p>

<p>
  <strong>Horas:</strong>
  <%= @proyecto.horas %>
</p>


<p>
  <strong>Carreras:</strong>
  <% @proyecto.carreras.all.order(:iniciales).each do |carrera|
  %>
    <%= "#{carrera.iniciales}" %>
  <% end %>
</p>

<p>
  <strong>Semestres: </strong>
  <% "#{@proyecto.semestre_minimo} - #{@proyecto.semestre_max}" %>
</p>

<p>
  <strong>Requisitos adicionales:</strong>
  <%= @proyecto.requisitos %>
</p>

<p><strong>Horarios</strong></p>
<% if @is_admin %>
    <%= form_tag(new_horario_path, :method => 'get') do %>
        <%= hidden_field :get, :proyecto_id, :value => @proyecto.id %>
        <%= submit_tag 'Añadir horario' %>
    <% end %>
<% end %>
<% if @proyecto.horarios.size > 0 %>
    <div>
        <table>
            <% @proyecto.horarios.each do |horario| %>
                <tr>
                  <td>
                    <% horario.dia_horas.each do |dia_hora| %>
                        <%= "#{dia_hora.to_s}\n" %>
                    <% end %>
                  </td>
                  <% unless @is_admin %>
                    <td>
                        <% if Usuario.find(session[:usuario]['id']).is_assigned_to_horario horario %>
                            <%= form_tag({:controller => 'proyectos', :action => 'remove_user_from_wait_list'}, :method => 'post') do %>
                                <%= hidden_field :post, 'usuario_id', :value => session[:usuario]['id'] %>
                                <%= hidden_field :post, 'horario_id', :value => horario.id %>
                                <%= submit_tag 'Salir del horario' %>
                            <% end %>
                        <% else %>
                            <% if @proyecto.registro_inicio <= Time.now and @proyecto.registro_fin >= Time.now %>
                                <%= form_tag({:controller => 'proyectos', :action => 'add_user_to_wait_list'}, :method => 'post') do %>
                                    <%= hidden_field :post, 'usuario_id', :value => session[:usuario]['id'] %>
                                    <%= hidden_field :post, 'horario_id', :value => horario.id %>
                                    <%= submit_tag 'Registrarse al horario' %>
                                <% end %>
                            <% else %>
                                <b><%= 'Registro no disponible' %></b>
                            <% end %>
                        <% end %>
                    </td>
                  <% end %>
                  <% if @is_admin %>
                    <td>
                      <%= form_tag(new_dia_hora_path, :method => 'get') do %>
                          <%= hidden_field :get, :horario_id, :value => horario.id %>
                          <%= submit_tag 'Añadir día y hora' %>
                      <% end %>
                    </td>
                  <% end %>
                </tr>
            <% end %>
        </table>
    </div>
    <% if @is_admin %>
        <%= form_tag({:controller => 'proyectos', :action => 'get_lista_espera_for_proyecto'}, :method => 'post') do %>
            <%= hidden_field :post, :proyecto_id, :value => @proyecto.id %>
            <%= submit_tag 'Ver lista de espera' %>
        <% end %>
    <% end %>
<% end %>
<% if session[:admin] %>
    <%= link_to 'Editar proyecto', edit_proyecto_path(@proyecto) %>
<% end %>
<%= link_to 'Regresar a proyectos', proyectos_path %>