config/routes.rb
Rails.application.routes.draw do
  root :to => 'login#index'

  get 'login/login', :to => 'login#login'
  post 'login/do_login', :to => 'login#do_login'

  get  'login/admin_login', :to => 'login#admin_login'
  post 'login/do_admin_login', :to => 'login#do_admin_login'

  get 'proyectos/mis_proyectos', :to => 'proyectos#projects_for_user'
  post 'proyectos/remove_assignment', :to => 'proyectos#remove_user_from_wait_list'
  post 'proyectos/assign', :to => 'proyectos#add_user_to_wait_list'
  post 'proyectos/lista_espera', :to => 'proyectos#get_lista_espera_for_proyecto'
  post 'proyectos/asignar', :to => 'proyectos#approve_asignacion'

  get '/welcome/', :to => 'welcome#index'

  resources :welcome

  resources :dia_horas

  resources :horarios

  resources :proyecto_carreras

  resources :lista_espera_proyectos

  resources :admins

  resources :proyectos

  resources :ubicacions

  resources :carreras

  resources :usuarios

end

app/models/carrera.rb
class Carrera < ActiveRecord::Base
  has_many :usuario
  has_many :proyecto_carreras
  has_many :proyectos, :through => :proyecto_carreras
end

app/controllers/carreras_controller.rb
class CarrerasController < ApplicationController
  before_action :set_carrera, only: [:show, :edit, :update, :destroy]

  # GET /carreras
  # GET /carreras.json
  def index
    @carreras = Carrera.all
  end

  # GET /carreras/1
  # GET /carreras/1.json
  def show
  end

  # GET /carreras/new
  def new
    @carrera = Carrera.new
  end

  # GET /carreras/1/edit
  def edit
  end

  # POST /carreras
  # POST /carreras.json
  def create
    @carrera = Carrera.new(carrera_params)

    respond_to do |format|
      if @carrera.save
        format.html { redirect_to @carrera, notice: 'Carrera was successfully created.' }
        format.json { render :show, status: :created, location: @carrera }
      else
        format.html { render :new }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carreras/1
  # PATCH/PUT /carreras/1.json
  def update
    respond_to do |format|
      if @carrera.update(carrera_params)
        format.html { redirect_to @carrera, notice: 'Carrera was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrera }
      else
        format.html { render :edit }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carreras/1
  # DELETE /carreras/1.json
  def destroy
    @carrera.destroy
    respond_to do |format|
      format.html { redirect_to carreras_url, notice: 'Carrera was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrera
      @carrera = Carrera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrera_params
      params.require(:carrera).permit(:nombre, :iniciales, :semestres)
    end
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/views/carreras/_form.html.erb
<%= form_for(@carrera) do |f| %>
  <% if @carrera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carrera.errors.count, "error") %> prohibited this carrera from being saved:</h2>

      <ul>
      <% @carrera.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :iniciales %><br>
    <%= f.text_field :iniciales %>
  </div>
  <div class="field">
    <%= f.label :semestres %><br>
    <%= f.number_field :semestres %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carreras/edit.html.erb
<h1>Editing Carrera</h1>

<%= render 'form' %>

<%= link_to 'Show', @carrera %> |
<%= link_to 'Back', carreras_path %>

app/views/carreras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carreras</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Iniciales</th>
      <th>Semestres</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carreras.each do |carrera| %>
      <tr>
        <td><%= carrera.nombre %></td>
        <td><%= carrera.iniciales %></td>
        <td><%= carrera.semestres %></td>
        <td><%= link_to 'Show', carrera %></td>
        <td><%= link_to 'Edit', edit_carrera_path(carrera) %></td>
        <td><%= link_to 'Destroy', carrera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrera', new_carrera_path %>

app/views/carreras/new.html.erb
<h1>New Carrera</h1>

<%= render 'form' %>

<%= link_to 'Back', carreras_path %>

app/views/carreras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @carrera.nombre %>
</p>

<p>
  <strong>Iniciales:</strong>
  <%= @carrera.iniciales %>
</p>

<p>
  <strong>Semestres:</strong>
  <%= @carrera.semestres %>
</p>

<%= link_to 'Edit', edit_carrera_path(@carrera) %> |
<%= link_to 'Back', carreras_path %>