config/routes.rb
Rails.application.routes.draw do
  root :to => 'login#index'

  get 'login/login', :to => 'login#login'
  post 'login/do_login', :to => 'login#do_login'

  get  'login/admin_login', :to => 'login#admin_login'
  post 'login/do_admin_login', :to => 'login#do_admin_login'

  get 'proyectos/mis_proyectos', :to => 'proyectos#projects_for_user'
  post 'proyectos/remove_assignment', :to => 'proyectos#remove_user_from_wait_list'
  post 'proyectos/assign', :to => 'proyectos#add_user_to_wait_list'
  post 'proyectos/lista_espera', :to => 'proyectos#get_lista_espera_for_proyecto'
  post 'proyectos/asignar', :to => 'proyectos#approve_asignacion'

  get '/welcome/', :to => 'welcome#index'

  resources :welcome

  resources :dia_horas

  resources :horarios

  resources :proyecto_carreras

  resources :lista_espera_proyectos

  resources :admins

  resources :proyectos

  resources :ubicacions

  resources :carreras

  resources :usuarios

end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  has_many :proyectos
end

app/controllers/ubicacions_controller.rb
class UbicacionsController < ApplicationController
  before_action :set_ubicacion, only: [:show, :edit, :update, :destroy]

  # GET /ubicacions
  # GET /ubicacions.json
  def index
    @ubicacions = Ubicacion.all
  end

  # GET /ubicacions/1
  # GET /ubicacions/1.json
  def show
  end

  # GET /ubicacions/new
  def new
    @ubicacion = Ubicacion.new
  end

  # GET /ubicacions/1/edit
  def edit
  end

  # POST /ubicacions
  # POST /ubicacions.json
  def create
    @ubicacion = Ubicacion.new(ubicacion_params)

    respond_to do |format|
      if @ubicacion.save
        format.html { redirect_to @ubicacion, notice: 'Ubicacion was successfully created.' }
        format.json { render :show, status: :created, location: @ubicacion }
      else
        format.html { render :new }
        format.json { render json: @ubicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ubicacions/1
  # PATCH/PUT /ubicacions/1.json
  def update
    respond_to do |format|
      if @ubicacion.update(ubicacion_params)
        format.html { redirect_to @ubicacion, notice: 'Ubicacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @ubicacion }
      else
        format.html { render :edit }
        format.json { render json: @ubicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ubicacions/1
  # DELETE /ubicacions/1.json
  def destroy
    @ubicacion.destroy
    respond_to do |format|
      format.html { redirect_to ubicacions_url, notice: 'Ubicacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ubicacion
      @ubicacion = Ubicacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ubicacion_params
      params.require(:ubicacion).permit(:name, :iniciales, :direccion, :descripcion, :maps)
    end
end

app/helpers/ubicacions_helper.rb
module UbicacionsHelper
end

app/views/ubicacions/_form.html.erb
<%= form_for(@ubicacion) do |f| %>
  <% if @ubicacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ubicacion.errors.count, "error") %> prohibited this ubicacion from being saved:</h2>

      <ul>
      <% @ubicacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :iniciales %><br>
    <%= f.text_field :iniciales %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :maps %><br>
    <%= f.text_field :maps %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ubicacions/edit.html.erb
<h1>Editing Ubicacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @ubicacion %> |
<%= link_to 'Back', ubicacions_path %>

app/views/ubicacions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ubicacions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Iniciales</th>
      <th>Direccion</th>
      <th>Descripcion</th>
      <th>Maps</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ubicacions.each do |ubicacion| %>
      <tr>
        <td><%= ubicacion.name %></td>
        <td><%= ubicacion.iniciales %></td>
        <td><%= ubicacion.direccion %></td>
        <td><%= ubicacion.descripcion %></td>
        <td><%= ubicacion.maps %></td>
        <td><%= link_to 'Show', ubicacion %></td>
        <td><%= link_to 'Edit', edit_ubicacion_path(ubicacion) %></td>
        <td><%= link_to 'Destroy', ubicacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ubicacion', new_ubicacion_path %>

app/views/ubicacions/new.html.erb
<h1>New Ubicacion</h1>

<%= render 'form' %>

<%= link_to 'Back', ubicacions_path %>

app/views/ubicacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ubicacion.name %>
</p>

<p>
  <strong>Iniciales:</strong>
  <%= @ubicacion.iniciales %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @ubicacion.direccion %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @ubicacion.descripcion %>
</p>

<p>
  <strong>Maps:</strong>
  <%= @ubicacion.maps %>
</p>

<%= link_to 'Edit', edit_ubicacion_path(@ubicacion) %> |
<%= link_to 'Back', ubicacions_path %>