config/routes.rb
Rails.application.routes.draw do
  root :to => 'login#index'

  get 'login/login', :to => 'login#login'
  post 'login/do_login', :to => 'login#do_login'

  get  'login/admin_login', :to => 'login#admin_login'
  post 'login/do_admin_login', :to => 'login#do_admin_login'

  get 'proyectos/mis_proyectos', :to => 'proyectos#projects_for_user'
  post 'proyectos/remove_assignment', :to => 'proyectos#remove_user_from_wait_list'
  post 'proyectos/assign', :to => 'proyectos#add_user_to_wait_list'
  post 'proyectos/lista_espera', :to => 'proyectos#get_lista_espera_for_proyecto'
  post 'proyectos/asignar', :to => 'proyectos#approve_asignacion'

  get '/welcome/', :to => 'welcome#index'

  resources :welcome

  resources :dia_horas

  resources :horarios

  resources :proyecto_carreras

  resources :lista_espera_proyectos

  resources :admins

  resources :proyectos

  resources :ubicacions

  resources :carreras

  resources :usuarios

end

app/models/horario.rb
class Horario < ActiveRecord::Base
  has_many :dia_horas
  belongs_to :proyecto

  has_many :lista_espera_proyectos
  has_many :usuarios, :through => :lista_espera_proyectos
end

app/controllers/horarios_controller.rb
class HorariosController < ApplicationController
  before_action :set_horario, only: [:show, :edit, :update, :destroy]

  # GET /horarios
  # GET /horarios.json
  def index
    @horarios = Horario.all
  end

  # GET /horarios/1
  # GET /horarios/1.json
  def show
  end

  # GET /horarios/new
  def new
    @horario = Horario.new
    @proyecto_id = params[:get][:proyecto_id] if params[:get] and params[:get][:proyecto_id]
  end

  # GET /horarios/1/edit
  def edit
  end

  # POST /horarios
  # POST /horarios.json
  def create
    @horario = Horario.new(horario_params)

    respond_to do |format|
      if @horario.save
        format.html { redirect_to @horario, notice: 'Horario was successfully created.' }
        format.json { render :show, status: :created, location: @horario }
      else
        format.html { render :new }
        format.json { render json: @horario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horarios/1
  # PATCH/PUT /horarios/1.json
  def update
    respond_to do |format|
      if @horario.update(horario_params)
        format.html { redirect_to @horario, notice: 'Horario was successfully updated.' }
        format.json { render :show, status: :ok, location: @horario }
      else
        format.html { render :edit }
        format.json { render json: @horario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horarios/1
  # DELETE /horarios/1.json
  def destroy
    @horario.destroy
    respond_to do |format|
      format.html { redirect_to horarios_url, notice: 'Horario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horario
      @horario = Horario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def horario_params
      params.require(:horario).permit(:capacidad, :proyecto_id)
    end
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/views/horarios/_form.html.erb
<%= form_for(@horario) do |f| %>
  <% if @horario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@horario.errors.count, "error") %> prohibited this horario from being saved:</h2>

      <ul>
      <% @horario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <ul>
        <% @horario.dia_horas.each do |dia_hora| %>
            <li><%= dia_hora.to_s %></li>
        <% end %>
    </ul>
    <br>
  </div>

  <div class="field">
    <%= f.label :capacidad %><br>
    <%= f.number_field :capacidad %>
  </div>
  <div class="field">
    <%= f.label :proyecto_id %><br>
    <%= f.select :proyecto_id, options_from_collection_for_select(Proyecto.all, :id, :nombre, @proyecto_id) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/horarios/edit.html.erb
<h1>Editing Horario</h1>

<%= render 'form' %>

<%= link_to 'Ver', @horario %> |
<%= link_to 'Regresar a proyecto', @horario.proyecto %>

app/views/horarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Horarios</h1>

<table>
  <thead>
    <tr>
      <th>Capacidad</th>
      <th>Proyecto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @horarios.each do |horario| %>
      <tr>
        <td><%= horario.capacidad %></td>
        <td><%= horario.proyecto_id %></td>
        <td><%= link_to 'Show', horario %></td>
        <td><%= link_to 'Edit', edit_horario_path(horario) %></td>
        <td><%= link_to 'Destroy', horario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Horario', new_horario_path %>

app/views/horarios/new.html.erb
<h1>Nuevo Horario</h1>

<%= render 'form' %>

<%= link_to 'Regresar a proyectos', proyectos_path %>

app/views/horarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Capacidad:</strong>
  <%= @horario.capacidad %>
</p>

<p>
  <strong>Proyecto:</strong>
  <%= link_to @horario.proyecto.nombre, @horario.proyecto %>
</p>

<p>
  <%= form_tag(new_dia_hora_path, :method => 'get') do %>
    <%= hidden_field :get, :horario_id, :value => @horario.id %>
    <%= submit_tag 'Añadir día y horario' %>
  <% end %>
</p>

<%= link_to 'Edit', edit_horario_path(@horario) %> |
<%= link_to 'Back', horarios_path %>